### ISSUE TITLE
String data, right truncated: 1406 Data too long for column 'uuid'

### ISSUE THREAD

**Issue by simondavies** [michaeldyrynda/laravel-efficient-uuid#1]
using the repo in conjunction with your other `laravel-model-uuid`repo.  But I am getting the following error:

`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'uuid' at row 1 (SQL: insert into...`

This happens when I try to run a seeder:

```php
         DB::table('pages')->insert([
            [
                'uuid' => Uuid::uuid4()->toString(),
                'parent_id' => 0,...
```
I ma using a local Ubuntu 16.04 local server, running MariaDB/MySQL 10.1.  

I think it's to do with adding the `Schema::defaultStringLength(191);`.

Is there a way around / fix this that I can implement.

**Comment by michaeldyrynda** [comment]
When using the DB facade directly, you'll want to use `Uuid::uuid4()->getBytes()`, I think, as this bypasses the model and subsequently the trait which handles casting.

Your data is getting truncated because `toString` returns a 36 character UUID string, which you're inserting into a 16 character binary field. 

That should do the trick, but let me know how you go and I can update the readme accordingly.

**Comment by simondavies** [comment]
Thats brilliant thanks.

I changed my seeder as recommended and it worked.

```php
          DB::table('pages')->insert([
            [
                'uuid' => Uuid::uuid4()->getBytes(),
                'parent_id' => 0,
```
